@startuml "diagrama_caso_de_uso"

left to right direction

skinparam ActorBorderColor black
skinparam ActorBackgroundColor white
skinparam UsecaseBackgroundColor white
skinparam UsecaseBorderColor black
skinparam ArrowColor black


rectangle "Finansee" {
    (Realizar Login) as realizar_login
    (Cadastrar Usuário) as cadastrar_usuario
    (Gerenciar Usuário) as gerenciar_usuario
    (Gerenciar Despesas) as gerenciar_despesas
    (Gerenciar Categoria) as gerenciar_categoria
    (Visualizar Resumo das Despesas) as visualizar_resumo_despesas
    (Visualizar_gasto_mensal) as visualizar_gasto_mensal
    (Buscar Despesas) as buscar_despesas
    (Buscar Categorias) as buscar_categorias
    (Exportar Resumo Mensal) as exportar_resumo_mensal
    (Redefinir Senha) as redefinir_senha
    (Gerenciar Periodo) as gerenciar_periodo
    (Validar Informações) as validar_informacoes
}

' Atores
:Usuario: as usuario 

' Casos de uso relacionados ao usuario
usuario -- realizar_login
usuario -- gerenciar_usuario
usuario -up- cadastrar_usuario
usuario -- redefinir_senha

gerenciar_usuario ..> realizar_login: <<include>>

' Casos de uso relacionados as despesas
usuario -- gerenciar_despesas
usuario -- visualizar_resumo_despesas
usuario -- buscar_despesas
usuario -- exportar_resumo_mensal
usuario -- visualizar_gasto_mensal

gerenciar_despesas ..> realizar_login: <<include>>
visualizar_resumo_despesas ..> realizar_login: <<include>>
buscar_despesas ..> realizar_login: <<include>>
exportar_resumo_mensal ..> realizar_login <<include>>
visualizar_gasto_mensal ..> realizar_login <<include>>

' Casos de uso relacionados as categorias
usuario -- gerenciar_categoria
usuario -- buscar_categorias

gerenciar_categoria ..> realizar_login: <<include>>
buscar_categorias ..> realizar_login: <<include>>

@enduml