@startuml Diagrama Lógico

skinparam TableAttributeFontSize 12
skinparam TableFontSize 14
skinparam TableBorderColor black
skinparam ArrowColor black
skinparam ArrowFontSize 14

entity "Usuario" as usuario {
  + id : varchar(36) [pk, unique, not null]
  nome : varchar(255)
  email : varchar(255) [unique, not null]
  numero_de_telefone : varchar(20)
  data_de_aniversario : date
  senha : varchar(255) [not null]
  renda_fixa : decimal(10, 2)
  --
}

entity "Despesa" as despesa {
  + id : varchar(36) [pk, unique, not null]
  nome : varchar(255) [not null]
  valor : decimal(10, 2) [not null]
  descricao : text
  data : date [not null]
  status : enum('Paga', 'A Pagar') [not null]
  usuario_id : varchar(36) [fk, not null]
  categoria_id : varchar(36) [fk]
  --
}

entity "Categoria" as categoria {
  + id : varchar(36) [pk, unique, not null]
  nome : varchar(255) [unique, not null]
  descricao : text
  --
}

entity "Periodo" as periodo {
  + id : varchar(36) [pk, unique, not null]
  mes : date
  renda_do_mes : decimal(10, 2)
  saldo_do_mes : decimal(10, 2)
  usuario_id : varchar(36) [fk, not null]
  despesa_id : varchar(36) [fk]
  --
}

usuario ||--o{ despesa : possui
usuario ||--|{ periodo : possui
usuario ||--o{ categoria : gerencia
despesa }o--o{ categoria : pertence as
periodo ||--o{ despesa: contem

@enduml